sudo: false
language: node_js
node_js:
  - "6.9.5"
before_install:
  # Node project, so Ruby dependencies must be installed manually (see `govuk-lint`)
  - bundle install
script:
  - npm test
before_deploy:
  # Encrypted SSH config used to `push.sh` to Github (See `.travis/README.md`)
  - openssl aes-256-cbc -K $encrypted_909ac1036a94_key -iv $encrypted_909ac1036a94_iv -in .travis/govuk_frontend_toolkit_push.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - git remote add origin_ssh git@github.com:alphagov/govuk_frontend_toolkit.git
deploy:
  - provider: script
    script: './push.sh'
    on:
      branch: master
  - provider: script
    script: './trigger.sh'
    on:
      branch: master
